(setq use-package-verbose t)
(load (concat user-emacs-directory "init-bare.el"))
(load (concat user-emacs-directory "init-settings.el"))
(load (concat user-emacs-directory "init-main.el"))
;; (load (concat user-emacs-directory "init-test.el"))
